# Walltime Limit: hh:nn:ss
#PBS -l walltime=120:00:00

# Node and memory specs
#PBS -l nodes=1:ppn=8 -l pmem=16gb

# Mail: options are (a) aborted, (b) begins execution, (e) ends execution
#PBS -M rmills198@gmail.com
#PBS -m abe

# Job name:
#PBS -N Salmon

#Job array
#PBS -t 1-40

# keep output in real time
#PBS -k oe


######################################################################

# Executable commands go here. Make sure that mpirun -np and -npn match the
# number of processors you requested from PBS! If you are using ppn and want
# npn=2, then you can leave -np and -npn off and PBS will add it for you. If
# you want npn=1, then you have to request all of the processors on all of the
# nodes, and then force it to use less using -npn.

echo ------------------------------------------------------
echo PBS: qsub is running on $PBS_O_HOST
echo PBS: originating queue is $PBS_O_QUEUE
echo PBS: executing queue is $PBS_QUEUE
echo PBS: working directory is $PBS_O_WORKDIR
echo PBS: execution mode is $PBS_ENVIRONMENT
echo PBS: job identifier is $PBS_JOBID
echo PBS: job name is $PBS_JOBNAME
echo PBS: node file is $PBS_NODEFILE
echo PBS: current home directory is $PBS_O_HOME
echo PBS: PATH = $PBS_O_PATH
echo ------------------------------------------------------

source activate prokka
export PATH=$PATH:$HOME/Salmon-0.7.2_linux_x86_64/bin

base_dir=/projects/mills_11549/sequencing/shotgun_20180411/Combined_lanes/trimmomatic/bowtie2
Samples=${base_dir}/../ids.txt
Sample_list=`awk 'NR==a {print $1}' a=$PBS_ARRAYID ${Samples}`

#Perform salmon
salmon quant -i ${base_dir}/assembly/transcript_index --libType IU -1 ${base_dir}/${Sample_list}.R1.trimmed.filtered.fastq.gz -2 ${base_dir}/${Sample_list}.R2.trimmed.filtered.fastq.gz -o ${base_dir}/Salmon_quant/${Sample_list}.quant -p 8

